language: dart
sudo: false
dart:
  - 2.1.0
script:
  - set -e
  - dartanalyzer --fatal-infos --fatal-warnings ./
  - dartanalyzer --fatal-infos --fatal-warnings ./example
  - pub get
  - pub upgrade
  - pub run test test/rx_redux_test.dart
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
