name: rx_redux
description: Redux implementation based on Dart Stream, with the power of RxDart. Reactive redux store for Dart & Flutter.
version: 2.5.0
homepage: https://github.com/hoc081098/rx_redux.git
repository: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues

environment:
  sdk: '<4.0.0'

dependencies:
  meta: ^1.7.0
  rxdart_ext: ^0.2.3
  disposebag: ^1.5.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  rxdart: ^0.27.5
  built_collection: ^5.1.1
  tuple: ^2.0.0
