name: rx_redux
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  rxdart: ^0.22.0
  meta: ">=1.1.1 <2.0.0"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
