name: rx_redux
description: A library that manages state using Dart Stream. Redux implementation based on Dart Stream, with the power of RxDart.
version: 1.2.0
homepage: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  rxdart: ^0.24.1