name: rx_redux
description: Redux implementation based on Dart Stream, with the power of RxDart. Reactive redux store for Dart & Flutter.
version: 2.4.0
homepage: https://github.com/hoc081098/rx_redux.git
repository: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  rxdart_ext: ^0.1.2
  disposebag: ^1.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
  rxdart: ^0.27.2
  built_collection: ^5.1.1
  tuple: ^2.0.0
