name: rx_redux
description: A library that manages state using RxDart. Redux implementation based on RxDart
version: 1.0.1+1
homepage: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  rxdart: ^0.23.1
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
