name: rx_redux
description: Redux implementation based on Dart Stream, with the power of RxDart. Reactive redux store for Dart & Flutter.
version: 2.2.0-nullsafety.2
author: Petrus Nguyen Thai Hoc <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rx_redux.git
repository: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  distinct_value_connectable_stream: ^1.2.0-nullsafety.5
  disposebag: ^1.5.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
  rxdart: ^0.26.0-nullsafety.0
  built_collection: ^5.0.0-nullsafety.0
  tuple: ^2.0.0-nullsafety.0
