name: rx_redux
description: Redux implementation based on Dart Stream, with the power of RxDart. Reactive redux store for Dart & Flutter.
version: 2.3.0
author: Petrus Nguyen Thai Hoc <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rx_redux.git
repository: https://github.com/hoc081098/rx_redux.git
issue_tracker: https://github.com/hoc081098/rx_redux/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  distinct_value_connectable_stream: ^1.3.0
  disposebag: ^1.5.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
  rxdart: ^0.27.0
  built_collection: ^5.0.0
  tuple: ^2.0.0
