name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pub get

    - name: Analyze
      run: dartanalyzer --fatal-infos --fatal-warnings ./lib ./test

    - name: Format code
      run: dartfmt -n ./lib ./test --set-exit-if-changed

    - name: Active coverage
      run: pub global activate coverage

    - name: Run tests
      run: pub run test/rx_redux_test.dart

    - name: TODO
      run: dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit test/rx_redux_test.dart &

    - name: Collect coverage
      run: nohup pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates

    - name: Format coverage
      run: pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib

    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
